// Catalogue complet ORIGO (fournitures pour restaurants) — chaque client n'en voit qu'une sélection
const PEXELS = (id) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=640`

export const PRODUITS = [
  {
    id: 'bol-kraft-750',
    photo: PEXELS(12916868),
    nom: 'Bol kraft 750 ml',
    description: 'Bol carton kraft brun, spécial vente à emporter',
    unitesParCarton: 300,
    prixCarton: 58.0,
    categorie: 'Vaisselle jetable',
    stock: 42,
    seuilAlerte: 10,
  },
  {
    id: 'couvercle-bol-750',
    photo: PEXELS(32424228),
    nom: 'Couvercle PET 750 ml',
    description: 'Couvercle transparent pour bol kraft 750 ml',
    unitesParCarton: 300,
    prixCarton: 34.5,
    categorie: 'Vaisselle jetable',
    stock: 35,
    seuilAlerte: 10,
    remise: { seuil: 10, pourcent: 5 },
  },
  {
    id: 'gobelet-25',
    photo: PEXELS(8148643),
    nom: 'Gobelet carton 25 cl',
    description: 'Gobelet double paroi pour boissons chaudes',
    unitesParCarton: 1000,
    prixCarton: 62.0,
    categorie: 'Vaisselle jetable',
    stock: 18,
    seuilAlerte: 10,
  },
  {
    id: 'barquette-alu',
    photo: PEXELS(5724553),
    nom: 'Barquette alu + couvercle',
    description: 'Barquette aluminium 1 000 ml avec couvercle carton',
    unitesParCarton: 100,
    prixCarton: 27.0,
    categorie: 'Vaisselle jetable',
    stock: 0,
    seuilAlerte: 10,
  },
  {
    id: 'sac-kraft',
    photo: PEXELS(11348488),
    nom: 'Sac kraft poignées torsadées',
    description: 'Sac papier kraft brun, format moyen',
    unitesParCarton: 250,
    prixCarton: 44.0,
    categorie: 'Emballage & cuisine',
    stock: 24,
    seuilAlerte: 10,
    remise: { seuil: 10, pourcent: 5 },
  },
  {
    id: 'film-etirable',
    photo: PEXELS(7322628),
    nom: 'Film étirable pro 300 m',
    description: 'Film alimentaire en boîte distributrice',
    unitesParCarton: 6,
    prixCarton: 31.5,
    categorie: 'Emballage & cuisine',
    stock: 15,
    seuilAlerte: 10,
  },
  {
    id: 'papier-toilette',
    photo: PEXELS(3958193),
    nom: 'Papier toilette 2 plis',
    description: 'Rouleaux blancs double épaisseur',
    unitesParCarton: 96,
    prixCarton: 38.0,
    categorie: 'Hygiène & entretien',
    stock: 30,
    seuilAlerte: 10,
  },
  {
    id: 'bobine-essuyage',
    photo: PEXELS(11091978),
    nom: 'Bobine d’essuyage 800 formats',
    description: 'Bobine blanche à dévidage central',
    unitesParCarton: 2,
    prixCarton: 21.0,
    categorie: 'Hygiène & entretien',
    stock: 7,
    seuilAlerte: 10,
  },
  {
    id: 'serviettes-ouate',
    photo: '/produits/serviette-papier-blanc-2-plis.webp',
    nom: 'Serviettes ouate 2 plis',
    description: 'Serviettes blanches 30 × 30 cm',
    unitesParCarton: 2400,
    prixCarton: 46.0,
    categorie: 'Hygiène & entretien',
    stock: 26,
    seuilAlerte: 10,
  },
  {
    id: 'gants-nitrile',
    photo: PEXELS(7856715),
    nom: 'Gants nitrile taille M',
    description: 'Gants jetables non poudrés, usage alimentaire',
    unitesParCarton: 1000,
    prixCarton: 54.0,
    categorie: 'Hygiène & entretien',
    stock: 12,
    seuilAlerte: 10,
  },

  // --- Ajoutés depuis le fichier fournisseur du client (prix à saisir) ---
  {
    id: 'sac-poubelle-130l',
    photo: PEXELS(5994772),
    nom: 'Sac poubelle 130 L',
    description: 'Sac poubelle très grand format, vendu au paquet',
    unitesParCarton: 1,
    prixCarton: 0,
    categorie: 'Hygiène & entretien',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'sac-poubelle-60l',
    photo: PEXELS(5994772),
    nom: 'Sac poubelle 60 L',
    description: 'Sac poubelle format standard, vendu au paquet',
    unitesParCarton: 1,
    prixCarton: 0,
    categorie: 'Hygiène & entretien',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'gant-noir-multitaille',
    photo: PEXELS(7337786),
    nom: 'Gant noir (S/M/L/XL)',
    description: 'Gants noirs jetables, carton de 100, tailles S à XL',
    unitesParCarton: 100,
    prixCarton: 0,
    categorie: 'Hygiène & entretien',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'rouleau-caisse-thermique',
    photo: PEXELS(12935090),
    nom: 'Rouleau caisse thermique',
    description: 'Rouleaux pour caisse et TPE, carton de 50',
    unitesParCarton: 50,
    prixCarton: 0,
    categorie: 'Emballage & cuisine',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'film-alimentaire-recharge-30cm',
    photo: PEXELS(7322628),
    nom: 'Film alimentaire recharge 30 cm 800 g',
    description: 'Recharge de film alimentaire 30 cm, boîte de 4',
    unitesParCarton: 4,
    prixCarton: 0,
    categorie: 'Emballage & cuisine',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'film-alimentaire-45cm-9micron',
    photo: PEXELS(7322628),
    nom: 'Film alimentaire 45 cm 9 microns',
    description: 'Film alimentaire 45 cm, 9 microns, boîte de 4',
    unitesParCarton: 4,
    prixCarton: 0,
    categorie: 'Emballage & cuisine',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'rouleau-aluminium-1350g',
    photo: PEXELS(10221748),
    nom: 'Rouleau aluminium 1350 g',
    description: 'Rouleau de papier aluminium 1350 g, boîte de 6',
    unitesParCarton: 6,
    prixCarton: 0,
    categorie: 'Emballage & cuisine',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'couverts-bois-jetables',
    photo: PEXELS(4157297),
    nom: 'Couverts bois (fourchette/couteau/cuillère)',
    description: 'Assortiment de couverts en bois, carton de 1000',
    unitesParCarton: 1000,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'gobelet-carton-250ml',
    photo: PEXELS(8148643),
    nom: 'Gobelet carton 250 ml',
    description: 'Gobelet carton 25 cl, carton de 1000',
    unitesParCarton: 1000,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'paille-papier-blanche',
    photo: PEXELS(3693356),
    nom: 'Paille droite papier blanc',
    description: 'Paille droite en papier, boîte de 3000',
    unitesParCarton: 3000,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'serviette-blanche-33x33',
    photo: '/produits/serviette-papier-blanc-2-plis.webp',
    nom: 'Serviette blanche 33 × 33 cm',
    description: 'Serviette blanche 2 plis, pliage 1/4',
    unitesParCarton: 2000,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'set-de-table-personnalise',
    photo: PEXELS(14935583),
    nom: 'Set de table personnalisé',
    description: 'Set de table personnalisable, carton de 1000',
    unitesParCarton: 1000,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'shopper-kraft-petit',
    photo: PEXELS(11348488),
    nom: 'Shopper kraft petit format',
    description: 'Sac shopper kraft, petit format, carton de 250',
    unitesParCarton: 250,
    prixCarton: 0,
    categorie: 'Emballage & cuisine',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'shopper-kraft-grand',
    photo: PEXELS(11348488),
    nom: 'Shopper kraft grand format',
    description: 'Sac shopper kraft, grand format, carton de 250',
    unitesParCarton: 250,
    prixCarton: 0,
    categorie: 'Emballage & cuisine',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'sachet-pain-kraft-2p',
    photo: PEXELS(3943177),
    nom: 'Sachet pain kraft 2P blanc',
    description: 'Sachet à pain kraft blanc 2 plis, carton de 1000',
    unitesParCarton: 1000,
    prixCarton: 0,
    categorie: 'Emballage & cuisine',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'verre-couvercle-plastique',
    photo: PEXELS(29653664),
    nom: 'Verre + couvercle plastique',
    description: 'Verre plastique avec couvercle, carton de 1000',
    unitesParCarton: 1000,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'pot-sauce-emporter-couvercle',
    photo: PEXELS(33425417),
    nom: 'Pot sauce à emporter + couvercle',
    description: 'Pot à sauce à emporter avec couvercle plastique, carton de 1000 pots + 1000 couvercles',
    unitesParCarton: 1000,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'bol-salade-couvercle-1100ml',
    photo: PEXELS(17870826),
    nom: 'Bol de salade + couvercle 1100 ml',
    description: 'Bol salade avec couvercle 1100 ml, carton de 150',
    unitesParCarton: 150,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'bol-salade-couvercle-500ml',
    photo: PEXELS(17870826),
    nom: 'Bol de salade + couvercle 500 ml',
    description: 'Bol salade avec couvercle 500 ml, carton de 150',
    unitesParCarton: 150,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'bol-salade-couvercle-175-250ml',
    photo: PEXELS(17870826),
    nom: 'Bol de salade + couvercle 175/250 ml',
    description: 'Bol salade avec couvercle 175 ou 250 ml, carton de 150',
    unitesParCarton: 150,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'bouteille-bouchon-orange-250ml',
    photo: PEXELS(4443461),
    nom: 'Bouteille + bouchon orange 250 ml',
    description: 'Bouteille plastique avec bouchon orange 250 ml, carton de 150',
    unitesParCarton: 150,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'papier-non-graisse-tandoor',
    photo: PEXELS(33637744),
    nom: 'Papier non-graisse pour tandoor',
    description: 'Papier sulfurisé anti-graisse pour four tandoor',
    unitesParCarton: 1,
    prixCarton: 0,
    categorie: 'Emballage & cuisine',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'papier-aluminium-isolant',
    photo: PEXELS(10221748),
    nom: 'Papier aluminium isolant',
    description: 'Papier aluminium isolant — fabrication sur demande',
    unitesParCarton: 1,
    prixCarton: 0,
    categorie: 'Emballage & cuisine',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'raviers-frites',
    photo: PEXELS(31609724),
    nom: 'Ravier à frites',
    description: 'Barquette/ravier pour frites',
    unitesParCarton: 1,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'pot-sauce-sur-place-blanc',
    photo: PEXELS(33425417),
    nom: 'Pot de sauce sur place blanc',
    description: 'Pot à sauce blanc pour consommation sur place',
    unitesParCarton: 1,
    prixCarton: 0,
    categorie: 'Vaisselle jetable',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'rouleau-papier-sachet6',
    photo: PEXELS(11091978),
    nom: 'Rouleau de papier',
    description: 'Rouleau de papier, sachet de 6 rouleaux',
    unitesParCarton: 6,
    prixCarton: 0,
    categorie: 'Hygiène & entretien',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'papier-zigzag-h2-h3',
    photo: PEXELS(11091978),
    nom: 'Papier zigzag H2/H3',
    description: 'Papier essuie-mains zigzag, formats H2 ou H3 selon fournisseur',
    unitesParCarton: 1,
    prixCarton: 0,
    categorie: 'Hygiène & entretien',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'papier-wc-mini-jumbo',
    photo: PEXELS(3958193),
    nom: 'Papier WC mini jumbo',
    description: 'Papier toilette mini jumbo, sachet de 12 rouleaux',
    unitesParCarton: 12,
    prixCarton: 0,
    categorie: 'Hygiène & entretien',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'savon-main-antibacterien',
    photo: PEXELS(4008464),
    nom: 'Savon main antibactérien 5/6 L',
    description: 'Savon mains antibactérien, bidon de 5 ou 6 L',
    unitesParCarton: 1,
    prixCarton: 0,
    categorie: 'Hygiène & entretien',
    stock: 20,
    seuilAlerte: 10,
  },
  {
    id: 'savon-main-clients',
    photo: PEXELS(4008464),
    nom: 'Savon main clients 5/6 L',
    description: 'Savon mains clients, bidon de 5 ou 6 L',
    unitesParCarton: 1,
    prixCarton: 0,
    categorie: 'Hygiène & entretien',
    stock: 20,
    seuilAlerte: 10,
  },
]

// Comptes clients — chaque client a un catalogue établi en amont avec ORIGO
export const CLIENTS = [
  {
    id: 'bombay',
    nom: 'Le Bombay',
    ville: 'Paris 11e',
    code: 'BOMBAY',
    motDePasse: '1234',
    email: 'contact@lebombay.fr',
    produits: ['bol-kraft-750', 'couvercle-bol-750', 'sac-kraft', 'serviettes-ouate', 'papier-toilette'],
    prix: {},
    favoris: [],
    notes: {},
    minCartons: 5,
  },
  {
    id: 'marco',
    nom: 'Chez Marco',
    ville: 'Lyon 3e',
    code: 'MARCO',
    motDePasse: '1234',
    email: 'commande@chezmarco.fr',
    produits: ['gobelet-25', 'barquette-alu', 'film-etirable', 'bobine-essuyage', 'gants-nitrile'],
    prix: {},
    favoris: [],
    notes: {},
    minCartons: 5,
  },
]

// Comptes entreprise ORIGO — invisibles côté client
// direction : accès complet · preparation : commandes et tournées uniquement
export const ADMINS = [
  { id: 'admin', code: 'ORIGO', motDePasse: 'admin2026', nom: 'Direction', role: 'direction' },
  { id: 'prepa', code: 'PREPA', motDePasse: 'prepa2026', nom: 'Préparation', role: 'preparation' },
]

// Prix appliqué à un client : tarif négocié s'il existe, sinon prix catalogue
export const prixPour = (client, produit) => client?.prix?.[produit.id] ?? produit.prixCarton

// Pourcentage de réduction qu'un prix par carton représente par rapport au
// prix de référence (négocié ou catalogue) — calculé automatiquement à
// partir du prix saisi par l'admin, jamais saisi directement.
export const pourcentagePalier = (pu, prixPalier) => (pu > 0 ? Math.round((1 - prixPalier / pu) * 100) : 0)

// Formate un pourcentage de remise en tenant compte du cas (rare, erreur de
// saisie) où le prix palier serait plus élevé que le prix de référence.
export const formatPourcentage = (pct) => (pct >= 0 ? `−${pct} %` : `+${Math.abs(pct)} %`)

// Tarif d'une ligne de panier, remise dégressive comprise.
// Un client peut avoir des paliers de prix par tranche libre (ex. 55 €/
// carton dès 20, 52 € dès 40…) : le palier le plus élevé atteint remplace
// le prix négocié et la remise produit, plutôt que de s'y ajouter. Le
// pourcentage affiché au client est déduit du prix, pas saisi par l'admin.
export function tarifLigne(client, produit, qty) {
  const pu = prixPour(client, produit)
  const paliers = client?.paliers?.[produit.id]
  const palier = paliers?.filter((p) => qty >= p.seuil).sort((a, b) => b.seuil - a.seuil)[0]
  if (palier) {
    return {
      pu,
      remisePct: pourcentagePalier(pu, palier.prix),
      puFinal: palier.prix,
      total: palier.prix * qty,
      palierSeuil: palier.seuil,
    }
  }
  const remisePct = produit.remise && qty >= produit.remise.seuil ? produit.remise.pourcent : 0
  const puFinal = Math.round(pu * (1 - remisePct / 100) * 100) / 100
  return { pu, remisePct, puFinal, total: puFinal * qty }
}

// Fenêtre pendant laquelle un client peut modifier ou annuler seul sa commande
// (au-delà, ou si la préparation a commencé, seul l'admin peut intervenir)
export const DELAI_MODIFICATION_MS = 60 * 60 * 1000

export const CONTACT = {
  telephone: '+32 2 000 00 00',
  telephoneLien: 'tel:+3220000000',
  email: 'pro@origo.be',
  horaires: 'Lun – Ven · 8h00 – 18h00',
}

export const euros = (n) =>
  n.toLocaleString('fr-FR', { style: 'currency', currency: 'EUR' })
